server {
    listen 80;
    server_name 5.22.217.149;
    root /var/www/foxelli;
    location /.well-known/acme-challenge/ { try_files $uri =404; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    server_name 5.22.217.149;
    root /opt/foxelli/current/web;
    index index.html;
    client_max_body_size 251m;
    ssl_certificate /etc/letsencrypt/live/5.22.217.149/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/5.22.217.149/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
